### ISSUE TITLE
Set/Hash access issue

### ISSUE THREAD

**Issue by nviennot** [ruby-amqp/bunny#206]
It seems that the Set `@unconfirmed_set` in `channel.rb` is modified while being enumerated at the same time. It would make sense that two different threads are accessing the set. Should we add Mutexes?

```
RuntimeError: can't add a new key into hash during iteration
/usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/set.rb:270:in `add'
/usr/local/rvm/gems/ruby-2.1.1/gems/bunny-1.2.0/lib/bunny/channel.rb:539:in `basic_publish'
/usr/local/rvm/gems/ruby-2.1.1/gems/bunny-1.2.0/lib/bunny/exchange.rb:145:in `publish'
```

**Comment by ndeloof** [comment]
Went into this issue (distinct execution stack):
```
~/vendor/bundle/ruby/3.0.0/gems/set-1.0.2/lib/set.rb:522:in `add': can't add a new key into hash during iteration (RuntimeError)
	from ~/vendor/bundle/ruby/3.0.0/gems/bunny-2.19.0/lib/bunny/channel.rb:555:in `block in basic_publish'
	from ~/vendor/bundle/ruby/3.0.0/gems/bunny-2.19.0/lib/bunny/channel.rb:554:in `synchronize'
	from ~/vendor/bundle/ruby/3.0.0/gems/bunny-2.19.0/lib/bunny/channel.rb:554:in `basic_publish'
	from ~/vendor/bundle/ruby/3.0.0/gems/bunny-2.19.0/lib/bunny/exchange.rb:141:in `publish'
	from ~/vendor/bundle/ruby/3.0.0/gems/bunny-2.19.0/lib/bunny/queue.rb:277:in `publish'
```
