### ISSUE TITLE
Thread not safe?

### ISSUE THREAD

**Issue by loveltyoic** [ruby-amqp/bunny#285]
```ruby
rabbitmq_connection = Bunny.new
rabbitmq_connection.start

c = rabbitmq_connection.create_channel

(1..10).map do |i|
  Thread.new do 
    c.fanout("herbert.fanout#{i}")
    c.queue("herbert.queue#{i}")
  end
end.each(&:join)
```

This will cause exception
```
NoMethodError: undefined method `queue' for #<AMQ::Protocol::Exchange::DeclareOk:0x007f8664489be8>
	from /Users/loveltyoic/.rvm/gems/ruby-2.1.5@xmly_home/gems/bunny-1.5.1/lib/bunny/queue.rb:363:in `declare!'
	from /Users/loveltyoic/.rvm/gems/ruby-2.1.5@xmly_home/gems/bunny-1.5.1/lib/bunny/queue.rb:52:in `initialize'
```

Then I find code in channel.rb, I guess this cause the problem:
```ruby
    def wait_on_continuations
      if @connection.threaded
        t = Thread.current
        @threads_waiting_on_continuations << t

        begin
          @continuations.poll(@connection.continuation_timeout)
        ensure
          @threads_waiting_on_continuations.delete(t)
        end
      else
        connection.reader_loop.run_once until @continuations.length > 0

        @continuations.pop
      end
    end
```

In multi thread situation, client receive declare ok out of order.
Is this a bug or I use it in a wrong way?

**Comment by michaelklishin** [comment]
Your code uses long time deprecated API methods from Bunny 0.8, which result in a channel being shared between threads.

Please [read the docs](http://rubybunny.info/articles/concurrency.html).

**Comment by loveltyoic** [comment]
Thanks for you explanation! Have not watched that articles before.
