### ISSUE TITLE
ThreadError: can't create Thread: Resource temporarily unavailable

### ISSUE THREAD

**Issue by whalesalad** [ruby-amqp/bunny#315]
```
ThreadError: can't create Thread: Resource temporarily unavailable
/app/vendor/bundle/ruby/2.2.0/gems/bunny-1.7.0/lib/bunny/concurrent/continuation_queue.rb:24:in `poll'
/app/vendor/bundle/ruby/2.2.0/gems/bunny-1.7.0/lib/bunny/channel.rb:1743:in `wait_on_continuations'
/app/vendor/bundle/ruby/2.2.0/gems/bunny-1.7.0/lib/bunny/channel.rb:1145:in `block in exchange_declare'
/app/vendor/bundle/ruby/2.2.0/gems/bunny-1.7.0/lib/bunny/channel.rb:1144:in `exchange_declare'
/app/vendor/bundle/ruby/2.2.0/gems/bunny-1.7.0/lib/bunny/exchange.rb:245:in `declare!'
/app/vendor/bundle/ruby/2.2.0/gems/bunny-1.7.0/lib/bunny/exchange.rb:83:in `initialize'
/app/vendor/bundle/ruby/2.2.0/gems/bunny-1.7.0/lib/bunny/channel.rb:334:in `new'
/app/vendor/bundle/ruby/2.2.0/gems/bunny-1.7.0/lib/bunny/channel.rb:334:in `topic'
/app/lib/push_service/consumer.rb:18:in `initialize'
```

The source line in my codebase triggering this issue:

`@exchange = @channel.topic(EXCHANGE, durable: true)`

I'm struggling to figure out why this is happening. I am running this within Heroku via a Rake task. It dies immediately so i'm not sure how it could be actually running out of threads.

**Comment by whalesalad** [comment]
Programmer error. I had something inside of an infinite loop by mistake and did not catch it initially. Sorry!
