### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by robertdfrench** [ruby-amqp/bunny#352]
We have run into a strange issue -- we can get a simple python client using pika to connect to our broker, but cannot seem to get one written in ruby using Bunny to do so.

This python/pika client will connect without error and print any messages that are on the "hello" queue:
```python
#!/bin/env python
import pika

host = 'rmq1.bojack.horsem.an'
port = 5672

creds = pika.PlainCredentials('dummy', 'password')
connection = pika.BlockingConnection(pika.ConnectionParameters(host,
port, "/dummy", credentials=creds))
channel = connection.channel()

#Create queue
channel.queue_declare(queue='hello')

def callback(ch, method, properties, body):
        print " [x] Received %r" % (body,)

channel.basic_consume(callback, queue='hello', no_ack=True)
channel.start_consuming()

connection.close()
```
This ruby/bunny client, from the same machine to the same server, does not work:
```ruby
#!/bin/env ruby
require "rubygems"
require "bunny"

connection = Bunny.new(:host => "rmq1.bojack.horsem.an",
        :vhost => "dummy",
        :user => "dummy",
        :password => "password",
        :automatically_recover => false
        )
connection.start
ch = connection.create_channel
q = ch.queue("hello", :auto_delete => true)

puts "[*] Connected and waiting on messages"
q.subscribe(:block => true, :ack => true) do |delivery_info, metadata, payload|
  puts "[x] Received #{payload}"
end
```
It will bomb after `connection.start` with this error:

```
[frenchrd@box ~/Projects/aprun-log-forwarder]$ bundle exec ruby unencrypted-bunny-client.rb
E, [2015-09-23T17:20:29.369684 #24870] ERROR -- #<Bunny::Session:5780380 rats-report@rmq1.bojack.horsem.an:5672, vhost=dummy, hosts=[rmq1.bojack.horsem.an]>: Got an exception when receiving data: Connection reset by peer (Errno::ECONNRESET)
W, [2015-09-23T17:20:29.369876 #24870]  WARN -- #<Bunny::Session:5780380 rats-report@rmq1.bojack.horsem.an:5672, vhost=dummy, hosts=[rmq1.bojack.horsem.an]>: An empty frame was received while opening the connection. In RabbitMQ <= 3.1 this could mean an authentication issue.
/autofs/nccs-svm1_home2/frenchrd/Projects/aprun-log-forwarder/vendor/bundle/ruby/2.1.0/gems/bunny-1.7.1/lib/bunny/session.rb:303:in `rescue in start': Could not establish TCP connection to any of the configured hosts (Bunny::TCPConnectionFailedForAllHosts)
        from /autofs/nccs-svm1_home2/frenchrd/Projects/aprun-log-forwarder/vendor/bundle/ruby/2.1.0/gems/bunny-1.7.1/lib/bunny/session.rb:265:in `start'
        from unencrypted-bunny-client.rb:12:in `<main>'
```

Do you have any ideas, or can you recommend any additional debugging strategies? Most of what we've read online (and in issues on this repo) indicates, quite fairly, that this is symptomatic of a network error -- what puzzles us is that the pika client is not giving us similar problems.

Thanks for your time.

**Comment by carlhoerberg** [comment]
You're trying to connect to vhost "/dummy" in pika but "dummy" in Bunny, note the extra slash.

**Comment by michaelklishin** [comment]
Please ask questions on the mailing list(s) and check RabbitMQ logs when in doubt. This particular mistake produces a reasonably suggestive message in the log:

```
=ERROR REPORT==== 24-Sep-2015::00:37:05 ===
closing AMQP connection <0.306.0> (127.0.0.1:55301 -> 127.0.0.1:5672):
{handshake_error,opening,0,
                 {amqp_error,access_refused,
                             "access to vhost 'skhskjdhfsdf' refused for user 'guest'",
                             'connection.open'}}
```

**Comment by robertdfrench** [comment]
Thanks @michaelklishin and @carlhoerberg, that was super helpful.
