### ISSUE TITLE
Session#create_channel can fail due to concurrent iteration/modification during connection recovery

### ISSUE THREAD

**Issue by mrgonza78** [ruby-amqp/bunny#407]
It seems that Session@channels is modified while being enumerated at the same time.

```
RuntimeError: can't add a new key into hash during iteration
    from /Users/alejandrog/deviget/ring/lpd-service/.bundle/gems/bunny-2.3.1/lib/bunny/session.rb:883:in `block in register_channel'
    from /Users/alejandrog/.rbenv/versions/2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
    from /Users/alejandrog/deviget/ring/lpd-service/.bundle/gems/bunny-2.3.1/lib/bunny/session.rb:882:in `register_channel'
    from /Users/alejandrog/deviget/ring/lpd-service/.bundle/gems/bunny-2.3.1/lib/bunny/channel.rb:174:in `initialize'
    from /Users/alejandrog/deviget/ring/lpd-service/.bundle/gems/bunny-2.3.1/lib/bunny/session.rb:346:in `new'
    from /Users/alejandrog/deviget/ring/lpd-service/.bundle/gems/bunny-2.3.1/lib/bunny/session.rb:346:in `block in create_channel'
    from /Users/alejandrog/.rbenv/versions/2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
    from /Users/alejandrog/deviget/ring/lpd-service/.bundle/gems/bunny-2.3.1/lib/bunny/session.rb:342:in `create_channel'
    from (irb):50
```

This occurred trying to create a channel while the session was recovering from a network failure.

Looking at the code I think this can come from Session#recover_channels, that iterates them while recovering after a network failure.

I can randomly reproduce it, I'll try to get it in an script.

**Comment by michaelklishin** [comment]
If this happens during channel recovery we probably can do something about it.

**Comment by mrgonza78** [comment]
It is not a pure scenario since this is a race condition error and I had to add an sleep in Bunny::Session#recover_channels in order to 'force' the race condition, and be able to reproduce the error consisntenly.

I think it shows the point ..

```
require 'bunny'

class Bunny::Session
  def recover_channels
    @channels.each do |n, ch|
      puts "go and create a new channel now!"
      sleep 5
      ch.open
      ch.recover_from_network_failure
    end
  end
end

session = Bunny.new.tap(&:start)

session.create_channel

#  Here is where I restart rabbitMQ , the following is ouput in the console...
#  W, [2016-05-21T17:00:24.482436 #63356]  WARN -- #<Bunny::Session:0x7fd99924aea8 guest@127.0.0.1:5672, vhost=/, addresses=[127.0.0.1:5672]>: Recovering from connection.close (CONNECTION_FORCED - broker forced connection closure with reason 'shutdown')
#  W, [2016-05-21T17:00:24.482684 #63356]  WARN -- #<Bunny::Session:0x7fd99924aea8 guest@127.0.0.1:5672, vhost=/, addresses=[127.0.0.1:5672]>: Recovering from a network failure...
#  W, [2016-05-21T17:00:34.491057 #63356]  WARN -- #<Bunny::Session:0x7fd99924aea8 guest@127.0.0.1:5672, vhost=/, addresses=[127.0.0.1:5672]>: Retrying connection on next host in line: 127.0.0.1:5672
#  go and create a new channel now!

session.create_channel

# RuntimeError: can't add a new key into hash during iteration
#   from /Users/alejandrog/deviget/ring/lpd-service/.bundle/gems/bunny-2.3.1/lib/bunny/session.rb:885:in `block in register_channel'
#   from /Users/alejandrog/.rbenv/versions/2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
#   from /Users/alejandrog/deviget/ring/lpd-service/.bundle/gems/bunny-2.3.1/lib/bunny/session.rb:884:in `register_channel'
#   from /Users/alejandrog/deviget/ring/lpd-service/.bundle/gems/bunny-2.3.1/lib/bunny/channel.rb:174:in `initialize'
#   from /Users/alejandrog/deviget/ring/lpd-service/.bundle/gems/bunny-2.3.1/lib/bunny/session.rb:346:in `new'
#   from /Users/alejandrog/deviget/ring/lpd-service/.bundle/gems/bunny-2.3.1/lib/bunny/session.rb:346:in `block in create_channel'
#   from /Users/alejandrog/.rbenv/versions/2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
#   from /Users/alejandrog/deviget/ring/lpd-service/.bundle/gems/bunny-2.3.1/lib/bunny/session.rb:342:in `create_channel'
#   from (irb):18
#   from /Users/alejandrog/.rbenv/versions/2.2.3/bin/irb:11:in `<main>'
```

**Comment by arsenische** [comment]
We encountered exactly the same issue with Bunny 2.5.0

**Comment by cavneb** [comment]
+1 we are also having the same problems

**Comment by brianbroderick** [comment]
This was causing errors 42% of the time.  Because of this, we had to switch to JRuby and use March Hare.  We were using Bunny 2.5.0.

**Comment by ghempton** [comment]
We have been hitting this issue as well.

**Comment by michaelklishin** [comment]
@mrgonza78 @cavneb @brianbroderick @ghempton I believe this is addressed in master. Can you please give it a shot and let me know how it goes? Thanks.
