### ISSUE TITLE
When both "host" and "hosts" options are present, it only tries to connect to `host`

### ISSUE THREAD

**Issue by sullerandras** [ruby-amqp/bunny#453]
When I pass both `host` and `hosts` options, Bunny prints a warning `The connection options contain both a host and an array of hosts, the single host is ignored.`
I think the message means that only the `hosts` option will be used, but that's not what happens. Bunny never tries to connect to any of the `hosts`, it only tries the single host.

Bunny 2.6.2 and Ruby 2.3 on Mac OS X.

It only tries to connect to the single host when both `host` and `hosts` are given:

```ruby
/Users/andras$ irb
2.3.1 :001 > require 'bunny'
 => true
2.3.1 :002 > Bunny.new(host: 'rabbit', hosts: ['host01', 'host02']).start
W, [2017-01-04T11:22:34.533145 #63295]  WARN -- #<Bunny::Session:0x7fc19383dc48 @rabbit:5672, vhost=, addresses=[rabbit:5672]>: The connection options contain both a host and an array of hosts, the single host is ignored.
W, [2017-01-04T11:22:34.534824 #63295]  WARN -- #<Bunny::Session:0x7fc19383dc48 guest@rabbit:5672, vhost=/, addresses=[rabbit:5672]>: Could not establish TCP connection to rabbit:5672: getaddrinfo: nodename nor servname provided, or not known
Bunny::TCPConnectionFailedForAllHosts: Could not establish TCP connection to any of the configured hosts
	from /Users/andras/.rvm/gems/ruby-2.3.1/gems/bunny-2.6.2/lib/bunny/session.rb:319:in 'rescue in start'
	from /Users/andras/.rvm/gems/ruby-2.3.1/gems/bunny-2.6.2/lib/bunny/session.rb:287:in 'start'
	from (irb):2
	from /Users/andras/.rvm/rubies/ruby-2.3.1/bin/irb:11:in '<main>'
2.3.1 :003 > Bunny.new(host: 'rabbit', addresses: ['host01:5678', 'host02:6789']).start
W, [2017-01-04T11:23:01.845207 #63295]  WARN -- #<Bunny::Session:0x7fc193adbb80 @rabbit:5672, vhost=, addresses=[rabbit:5672]>: The connection options contain both a host and an array of hosts, the single host is ignored.
W, [2017-01-04T11:23:01.846172 #63295]  WARN -- #<Bunny::Session:0x7fc193adbb80 guest@rabbit:5672, vhost=/, addresses=[rabbit:5672]>: Could not establish TCP connection to rabbit:5672: getaddrinfo: nodename nor servname provided, or not known
Bunny::TCPConnectionFailedForAllHosts: Could not establish TCP connection to any of the configured hosts
	from /Users/andras/.rvm/gems/ruby-2.3.1/gems/bunny-2.6.2/lib/bunny/session.rb:319:in 'rescue in start'
	from /Users/andras/.rvm/gems/ruby-2.3.1/gems/bunny-2.6.2/lib/bunny/session.rb:287:in 'start'
	from (irb):3
	from /Users/andras/.rvm/rubies/ruby-2.3.1/bin/irb:11:in '<main>'
```

But it correctly tries all the hosts when there's no `host` option:

```ruby
2.3.1 :004 > Bunny.new(hosts: ['host01', 'host02']).start
W, [2017-01-04T11:26:01.776760 #63295]  WARN -- #<Bunny::Session:0x7fc193a6bec0 guest@host02:5672, vhost=/, addresses=[host02:5672,host01:5672]>: Could not establish TCP connection to host02:5672: getaddrinfo: nodename nor servname provided, or not known
W, [2017-01-04T11:26:01.776825 #63295]  WARN -- #<Bunny::Session:0x7fc193a6bec0 guest@host01:5672, vhost=/, addresses=[host02:5672,host01:5672]>: Will try to connect to the next endpoint in line: host01:5672
W, [2017-01-04T11:26:01.777469 #63295]  WARN -- #<Bunny::Session:0x7fc193a6bec0 guest@host01:5672, vhost=/, addresses=[host02:5672,host01:5672]>: Could not establish TCP connection to host01:5672: getaddrinfo: nodename nor servname provided, or not known
Bunny::TCPConnectionFailedForAllHosts: Could not establish TCP connection to any of the configured hosts
	from /Users/andras/.rvm/gems/ruby-2.3.1/gems/bunny-2.6.2/lib/bunny/session.rb:319:in 'rescue in start'
	from /Users/andras/.rvm/gems/ruby-2.3.1/gems/bunny-2.6.2/lib/bunny/session.rb:287:in 'start'
	from /Users/andras/.rvm/gems/ruby-2.3.1/gems/bunny-2.6.2/lib/bunny/session.rb:311:in 'rescue in start'
	from /Users/andras/.rvm/gems/ruby-2.3.1/gems/bunny-2.6.2/lib/bunny/session.rb:288:in 'start'
	from (irb):7
	from /Users/andras/.rvm/rubies/ruby-2.3.1/bin/irb:11:in '<main>'
2.3.1 :005 > Bunny.new(addresses: ['host01:5678', 'host02:6789']).start
W, [2017-01-04T11:25:51.041066 #63295]  WARN -- #<Bunny::Session:0x7fc193a8b1a8 guest@host02:6789, vhost=/, addresses=[host02:6789,host01:5678]>: Could not establish TCP connection to host02:6789: getaddrinfo: nodename nor servname provided, or not known
W, [2017-01-04T11:25:51.041118 #63295]  WARN -- #<Bunny::Session:0x7fc193a8b1a8 guest@host01:5678, vhost=/, addresses=[host02:6789,host01:5678]>: Will try to connect to the next endpoint in line: host01:5678
W, [2017-01-04T11:25:51.041782 #63295]  WARN -- #<Bunny::Session:0x7fc193a8b1a8 guest@host01:5678, vhost=/, addresses=[host02:6789,host01:5678]>: Could not establish TCP connection to host01:5678: getaddrinfo: nodename nor servname provided, or not known
Bunny::TCPConnectionFailedForAllHosts: Could not establish TCP connection to any of the configured hosts
	from /Users/andras/.rvm/gems/ruby-2.3.1/gems/bunny-2.6.2/lib/bunny/session.rb:319:in 'rescue in start'
	from /Users/andras/.rvm/gems/ruby-2.3.1/gems/bunny-2.6.2/lib/bunny/session.rb:287:in 'start'
	from /Users/andras/.rvm/gems/ruby-2.3.1/gems/bunny-2.6.2/lib/bunny/session.rb:311:in 'rescue in start'
	from /Users/andras/.rvm/gems/ruby-2.3.1/gems/bunny-2.6.2/lib/bunny/session.rb:288:in 'start'
	from (irb):6
	from /Users/andras/.rvm/rubies/ruby-2.3.1/bin/irb:11:in '<main>'
```

**Comment by michaelklishin** [comment]
Use one or the other. Using both makes little sense.

**Comment by sullerandras** [comment]
I was hoping for a cleaner warning message. Can we drop the `the single host is ignored` part? Or change it to `the single host will be used`?

**Comment by michaelklishin** [comment]
https://github.com/ruby-amqp/bunny/commit/e15cf58e431d88489521cdf1d22334dc9135a86d
