### ISSUE TITLE
Throws Exception AMQ::Protocol::EmptyResponseError: Empty response on retries

### ISSUE THREAD

**Issue by kavitakanojiya** [ruby-amqp/bunny#459]
Hey,

We have sneakers(2.5.0.pre) with bunny (2.6) added in our system. After few attempts, it starts throwing following errors:

```
W, [2017-01-24T07:55:21.880479 #8768]  WARN -- #<Bunny::Session:0x559f17da0398 edcastadmin@rabbitmq-production.edcast.com:5672, vhost=/, addresses=[rabbitmq-production.edcast.com:5672]>: Recovering from a network failure...
W, [2017-01-24T07:55:22.281774 #8768]  WARN -- #<Bunny::Session:0x559f17da0398 edcastadmin@rabbitmq-production.edcast.com:5672, vhost=/, addresses=[rabbitmq-production.edcast.com:5672]>: Retrying connection on next host in line: rabbitmq-production.edcast.com:5672
E, [2017-01-24T07:56:26.417015 #8768] ERROR -- #<Bunny::Session:0x559f17da0398 edcastadmin@rabbitmq-production.edcast.com:5672, vhost=/, addresses=[rabbitmq-production.edcast.com:5672]>: Exception in the reader loop: AMQ::Protocol::EmptyResponseError: Empty response received from the server.
E, [2017-01-24T07:56:26.417085 #8768] ERROR -- #<Bunny::Session:0x559f17da0398 edcastadmin@rabbitmq-production.edcast.com:5672, vhost=/, addresses=[rabbitmq-production.edcast.com:5672]>: Backtrace: 
E, [2017-01-24T07:56:26.417130 #8768] ERROR -- #<Bunny::Session:0x559f17da0398 edcastadmin@rabbitmq-production.edcast.com:5672, vhost=/, addresses=[rabbitmq-production.edcast.com:5672]>: 	/usr/local/bundle/gems/amq-protocol-2.0.1/lib/amq/protocol/frame.rb:60:in `decode_header'
E, [2017-01-24T07:56:26.417151 #8768] ERROR -- #<Bunny::Session:0x559f17da0398 edcastadmin@rabbitmq-production.edcast.com:5672, vhost=/, addresses=[rabbitmq-production.edcast.com:5672]>: 	/usr/local/bundle/gems/bunny-2.6.2/lib/bunny/transport.rb:245:in `read_next_frame'
E, [2017-01-24T07:56:26.417168 #8768] ERROR -- #<Bunny::Session:0x559f17da0398 edcastadmin@rabbitmq-production.edcast.com:5672, vhost=/, addresses=[rabbitmq-production.edcast.com:5672]>: 	/usr/local/bundle/gems/bunny-2.6.2/lib/bunny/reader_loop.rb:68:in `run_once'
E, [2017-01-24T07:56:26.417184 #8768] ERROR -- #<Bunny::Session:0x559f17da0398 edcastadmin@rabbitmq-production.edcast.com:5672, vhost=/, addresses=[rabbitmq-production.edcast.com:5672]>: 	/usr/local/bundle/gems/bunny-2.6.2/lib/bunny/reader_loop.rb:35:in `block in run_loop'
E, [2017-01-24T07:56:26.417200 #8768] ERROR -- #<Bunny::Session:0x559f17da0398 edcastadmin@rabbitmq-production.edcast.com:5672, vhost=/, addresses=[rabbitmq-production.edcast.com:5672]>: 	/usr/local/bundle/gems/bunny-2.6.2/lib/bunny/reader_loop.rb:32:in `loop'
E, [2017-01-24T07:56:26.417216 #8768] ERROR -- #<Bunny::Session:0x559f17da0398 edcastadmin@rabbitmq-production.edcast.com:5672, vhost=/, addresses=[rabbitmq-production.edcast.com:5672]>: 	/usr/local/bundle/gems/bunny-2.6.2/lib/bunny/reader_loop.rb:32:in `run_loop'
W, [2017-01-24T07:56:26.417243 #8768]  WARN -- #<Bunny::Session:0x559f17da0398 edcastadmin@rabbitmq-production.edcast.com:5672, vhost=/, addresses=[rabbitmq-production.edcast.com:5672]>: Recovering from a network failure...
W, [2017-01-24T07:56:26.818418 #8768]  WARN -- #<Bunny::Session:0x559f17da0398 edcastadmin@rabbitmq-production.edcast.com:5672, vhost=/, addresses=[rabbitmq-production.edcast.com:5672]>: Retrying connection on next host in line: rabbitmq-production.edcast.com:5672
E, [2017-01-24T07:57:30.416389 #8768] ERROR -- #<Bunny::Session:0x559f17da0398 edcastadmin@rabbitmq-production.edcast.com:5672, vhost=/, addresses=[rabbitmq-production.edcast.com:5672]>: Exception in the reader loop: AMQ::Protocol::EmptyResponseError: Empty response received from the server.
E, [2017-01-24T07:57:30.416476 #8768] ERROR -- #<Bunny::Session:0x559f17da0398 edcastadmin@rabbitmq-production.edcast.com:5672, vhost=/, addresses=[rabbitmq-production.edcast.com:5672]>: Backtrace: 
E, [2017-01-24T07:57:30.416520 #8768] ERROR -- #<Bunny::Session:0x559f17da0398 edcastadmin@rabbitmq-production.edcast.com:5672, vhost=/, addresses=[rabbitmq-production.edcast.com:5672]>: 	/usr/local/bundle/gems/amq-protocol-2.0.1/lib/amq/protocol/frame.rb:60:in `decode_header'
E, [2017-01-24T07:57:30.416543 #8768] ERROR -- #<Bunny::Session:0x559f17da0398 edcastadmin@rabbitmq-production.edcast.com:5672, vhost=/, addresses=[rabbitmq-production.edcast.com:5672]>: 	/usr/local/bundle/gems/bunny-2.6.2/lib/bunny/transport.rb:245:in `read_next_frame'
E, [2017-01-24T07:57:30.416560 #8768] ERROR -- #<Bunny::Session:0x559f17da0398 edcastadmin@rabbitmq-production.edcast.com:5672, vhost=/, addresses=[rabbitmq-production.edcast.com:5672]>: 	/usr/local/bundle/gems/bunny-2.6.2/lib/bunny/reader_loop.rb:68:in `run_once'
E, [2017-01-24T07:57:30.416571 #8768] ERROR -- #<Bunny::Session:0x559f17da0398 edcastadmin@rabbitmq-production.edcast.com:5672, vhost=/, addresses=[rabbitmq-production.edcast.com:5672]>: 	/usr/local/bundle/gems/bunny-2.6.2/lib/bunny/reader_loop.rb:35:in `block in run_loop'
E, [2017-01-24T07:57:30.416582 #8768] ERROR -- #<Bunny::Session:0x559f17da0398 edcastadmin@rabbitmq-production.edcast.com:5672, vhost=/, addresses=[rabbitmq-production.edcast.com:5672]>: 	/usr/local/bundle/gems/bunny-2.6.2/lib/bunny/reader_loop.rb:32:in `loop'
E, [2017-01-24T07:57:30.416592 #8768] ERROR -- #<Bunny::Session:0x559f17da0398 edcastadmin@rabbitmq-production.edcast.com:5672, vhost=/, addresses=[rabbitmq-production.edcast.com:5672]>: 	/usr/local/bundle/gems/bunny-2.6.2/lib/bunny/reader_loop.rb:32:in `run_loop'
W, [2017-01-24T07:57:30.416611 #8768]  WARN -- #<Bunny::Session:0x559f17da0398 edcastadmin@rabbitmq-production.edcast.com:5672, vhost=/, addresses=[rabbitmq-production.edcast.com:5672]>: Recovering from a network failure...
W, [2017-01-24T07:57:30.817726 #8768]  WARN -- #<Bunny::Session:0x559f17da0398 edcastadmin@rabbitmq-production.edcast.com:5672, vhost=/, addresses=[rabbitmq-production.edcast.com:5672]>: Retrying connection on next host in line: rabbitmq-production.edcast.com:5672
```

Due to this no further activity is done.
Can you help what wrong am I doing ?

Thanks.

**Comment by michaelklishin** [comment]
I suspect that it comes down to a network connectivity problem. You can see that it happens several times, and connection recovery kicks in only to effectively read an EOF shortly after. I don't have any data to suggest more.

**Comment by michaelklishin** [comment]
It may be a good idea to edit out your company's domain when posting logs. I will do it.

**Comment by michaelklishin** [comment]
You say "2.6" and I have no evidence that #456 may be involved but if you are on Ruby 2.1 or later, please upgrade to `2.6.2`.

**Comment by AnkitRathore175** [comment]
Hi @michaelklishin 
i m getting same kind of error in ruby 2.6.2 and bunny 2.9.2
i installed the Rabbitmq on remote machine and added user by below commands

```
rabbitmqctl add_user yourName yourPass
rabbitmqctl set_permissions -p / yourName ".*" ".*" ".*"
rabbitmqctl set_user_tags yourName administrator
```
And when i tried with 
`rabbitmqadmin -H X.X.X.X -u yourName -p yourPass -P 15672 list vhosts`
so it works fine
but when i try with bunny so it says 
`AMQ::Protocol::EmptyResponseError (Empty response received from the server.)`
and getting nothing in rabbitmq logs.
can you please help me what m I missing here?
thanks in advance

**Comment by michaelklishin** [comment]
This is not a support forum. Bunny has a mailing list. If there is nothing in target RabbitMQ node logs, then the connection likely [never happens](https://www.rabbitmq.com/logging.html#logged-events). See [Troubleshooting Networking](https://www.rabbitmq.com/troubleshooting-networking.html) and note that `rabbitmqadmin` uses  a [different port from Bunny](https://www.rabbitmq.com/networking.html#ports).

`rabbitmqctl authenticate_user` is also relevant here but if it was an [authentication failure](https://www.rabbitmq.com/access-control.html#troubleshooting-authn) there would be log messages about that (and Bunny itself would throw a specific exception).
