### ISSUE TITLE
amq-protocol needs to be locked to 2.2.0 for versions prior to 2.9.0

### ISSUE THREAD

**Issue by greggilbert** [ruby-amqp/bunny#538]
So we started getting these errors on our servers:

```
Unexpected error undefined method `>' for nil:NilClass
  /usr/local/rvm/gems/ruby-2.4.0/gems/bunny-2.6.6/lib/bunny/session.rb:1361:in `normalize_client_channel_max'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bunny-2.6.6/lib/bunny/session.rb:185:in `initialize'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bunny-2.6.6/lib/bunny.rb:66:in `new'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bunny-2.6.6/lib/bunny.rb:66:in `new'
  /usr/local/rvm/gems/ruby-2.4.0/gems/sneakers-2.5.0/lib/sneakers/queue.rb:65:in `create_bunny_connection'
  /usr/local/rvm/gems/ruby-2.4.0/gems/sneakers-2.5.0/lib/sneakers/queue.rb:22:in `subscribe'
  /usr/local/rvm/gems/ruby-2.4.0/gems/sneakers-2.5.0/lib/sneakers/worker.rb:107:in `run'
  /usr/local/rvm/gems/ruby-2.4.0/gems/sneakers-2.5.0/lib/sneakers/workergroup.rb:36:in `block in run'
  /usr/local/rvm/gems/ruby-2.4.0/gems/sneakers-2.5.0/lib/sneakers/workergroup.rb:35:in `each'
  /usr/local/rvm/gems/ruby-2.4.0/gems/sneakers-2.5.0/lib/sneakers/workergroup.rb:35:in `run'
```

We solved it by forcing `amq-protocol` to `2.2.0` in our local Gemfile, so it seems like this issue is caused by the upgrade to 2.3.0.

**Comment by michaelklishin** [comment]
Bunny 2.9.0 needs 2.3.0. I'd much rather see people use that but issuing releases for 2.8.x and 2.7.x that limit the dependency. Sorry but there is no reason to stay on 2.6.x.

**Comment by michaelklishin** [comment]
[Done](https://rubygems.org/gems/bunny).

**Comment by Dorian** [comment]
Happened to me today, with [sneakers](https://github.com/jondot/sneakers), adding `gem 'amq-protocol', '2.2.0'` to my Gemfile fixed it

**Comment by michaelklishin** [comment]
The right thing to do is to use the most recent version of Bunny if your other dependencies allow for that.
