### ISSUE TITLE
Should Timeout::Error from an I/O read trigger a connection recovery?

### ISSUE THREAD

**Issue by rgaufman** [ruby-amqp/bunny#548]
I got this on a few servers that were quite heavily loaded:

```
2018-04-03 13:34:41.671119 E [22564:49960800 transport.rb:216] TimelineMessaging::RabbitConnection -- Got an exception when receiving data: IO timeout when reading 7 bytes (Timeout::Error)
2018-04-03 13:35:13.373813 W [22564:49960800] TimelineMessaging::RabbitConnection -- Exception in the reader loop: Timeout::Error: IO timeout when reading 7 bytes
2018-04-03 13:35:13.373860 W [22564:49960800] TimelineMessaging::RabbitConnection -- Backtrace:
2018-04-03 13:35:13.579588 W [22564:49960800] TimelineMessaging::RabbitConnection -- 	/data/deployer/timeagent/vendor/bundle/ruby/2.5.0/gems/bunny-2.9.2/lib/bunny/cruby/socket.rb:65:in `rescue in read_fully'
2018-04-03 13:35:13.579650 W [22564:49960800] TimelineMessaging::RabbitConnection -- 	/data/deployer/timeagent/vendor/bundle/ruby/2.5.0/gems/bunny-2.9.2/lib/bunny/cruby/socket.rb:53:in `read_fully'
2018-04-03 13:35:13.579708 W [22564:49960800] TimelineMessaging::RabbitConnection -- 	/data/deployer/timeagent/vendor/bundle/ruby/2.5.0/gems/bunny-2.9.2/lib/bunny/transport.rb:214:in `read_fully'
2018-04-03 13:35:13.579731 W [22564:49960800] TimelineMessaging::RabbitConnection -- 	/data/deployer/timeagent/vendor/bundle/ruby/2.5.0/gems/bunny-2.9.2/lib/bunny/transport.rb:236:in `read_next_frame'
2018-04-03 13:35:13.579752 W [22564:49960800] TimelineMessaging::RabbitConnection -- 	/data/deployer/timeagent/vendor/bundle/ruby/2.5.0/gems/bunny-2.9.2/lib/bunny/reader_loop.rb:69:in `run_once'
2018-04-03 13:35:13.579774 W [22564:49960800] TimelineMessaging::RabbitConnection -- 	/data/deployer/timeagent/vendor/bundle/ruby/2.5.0/gems/bunny-2.9.2/lib/bunny/reader_loop.rb:35:in `block in run_loop'
2018-04-03 13:35:13.579795 W [22564:49960800] TimelineMessaging::RabbitConnection -- 	/data/deployer/timeagent/vendor/bundle/ruby/2.5.0/gems/bunny-2.9.2/lib/bunny/reader_loop.rb:32:in `loop'
2018-04-03 13:35:13.579817 W [22564:49960800] TimelineMessaging::RabbitConnection -- 	/data/deployer/timeagent/vendor/bundle/ruby/2.5.0/gems/bunny-2.9.2/lib/bunny/reader_loop.rb:32:in `run_loop'
2018-04-03 13:35:15.430825 W [22564:49960800] TimelineMessaging::RabbitConnection -- Will recover from a network failure (no retry limit)...
2018-04-03 13:35:21.183108 E [22564:48796040 transport.rb:216] TimelineMessaging::RabbitConnection -- Got an exception when receiving data: IO timeout when reading 7 bytes (Timeout::Error)
2018-04-03 13:35:21.183520 W [22564:48796040] TimelineMessaging::RabbitConnection -- Exception in the reader loop: Timeout::Error: IO timeout when reading 7 bytes
2018-04-03 13:35:21.183552 W [22564:48796040] TimelineMessaging::RabbitConnection -- Backtrace:
2018-04-03 13:35:21.183578 W [22564:48796040] TimelineMessaging::RabbitConnection -- 	/data/deployer/timeagent/vendor/bundle/ruby/2.5.0/gems/bunny-2.9.2/lib/bunny/cruby/socket.rb:65:in `rescue in read_fully'
2018-04-03 13:35:21.183600 W [22564:48796040] TimelineMessaging::RabbitConnection -- 	/data/deployer/timeagent/vendor/bundle/ruby/2.5.0/gems/bunny-2.9.2/lib/bunny/cruby/socket.rb:53:in `read_fully'
2018-04-03 13:35:21.183621 W [22564:48796040] TimelineMessaging::RabbitConnection -- 	/data/deployer/timeagent/vendor/bundle/ruby/2.5.0/gems/bunny-2.9.2/lib/bunny/transport.rb:214:in `read_fully'
2018-04-03 13:35:21.183642 W [22564:48796040] TimelineMessaging::RabbitConnection -- 	/data/deployer/timeagent/vendor/bundle/ruby/2.5.0/gems/bunny-2.9.2/lib/bunny/transport.rb:236:in `read_next_frame'
2018-04-03 13:35:21.183687 W [22564:48796040] TimelineMessaging::RabbitConnection -- 	/data/deployer/timeagent/vendor/bundle/ruby/2.5.0/gems/bunny-2.9.2/lib/bunny/reader_loop.rb:69:in `run_once'
2018-04-03 13:35:21.183711 W [22564:48796040] TimelineMessaging::RabbitConnection -- 	/data/deployer/timeagent/vendor/bundle/ruby/2.5.0/gems/bunny-2.9.2/lib/bunny/reader_loop.rb:35:in `block in run_loop'
2018-04-03 13:35:21.183732 W [22564:48796040] TimelineMessaging::RabbitConnection -- 	/data/deployer/timeagent/vendor/bundle/ruby/2.5.0/gems/bunny-2.9.2/lib/bunny/reader_loop.rb:32:in `loop'
2018-04-03 13:35:21.183754 W [22564:48796040] TimelineMessaging::RabbitConnection -- 	/data/deployer/timeagent/vendor/bundle/ruby/2.5.0/gems/bunny-2.9.2/lib/bunny/reader_loop.rb:32:in `run_loop'
2018-04-03 13:35:21.183805 W [22564:48796040] TimelineMessaging::RabbitConnection -- Will recover from a network failure (no retry limit)...
2018-04-03 13:35:47.997344 W [22564:48796040] TimelineMessaging::RabbitConnection -- Retrying connection on next host in line: localhost:5672
2018-04-03 13:35:48.768524 W [22564:49960800] TimelineMessaging::RabbitConnection -- Retrying connection on next host in line: localhost:5672
2018-04-03 13:36:02.483304 E [22564:49960800 transport.rb:142] TimelineMessaging::RabbitConnection -- Got an exception when sending data: Connection reset by peer (Errno::ECONNRESET)
2018-04-03 13:36:10.226127 E [22564:49960800 transport.rb:216] TimelineMessaging::RabbitConnection -- Got an exception when receiving data: closed stream (IOError)
2018-04-03 13:36:21.636635 E [22564:48796040 transport.rb:142] TimelineMessaging::RabbitConnection -- Got an exception when sending data: Connection reset by peer (Errno::ECONNRESET)
2018-04-03 13:36:21.858144 E [22564:48796040 transport.rb:216] TimelineMessaging::RabbitConnection -- Got an exception when receiving data: closed stream (IOError)
2018-04-03 13:36:22.769119 W [22564:48796040] TimelineMessaging::RabbitConnection -- An empty frame was received while opening the connection. In RabbitMQ <= 3.1 this could mean an authentication issue.
2018-04-03 13:36:23.000645 W [22564:48796040] TimelineMessaging::RabbitConnection -- TCP connection failed, reconnecting in 5.0 seconds
2018-04-03 13:36:23.000850 W [22564:48796040] TimelineMessaging::RabbitConnection -- Will recover from a network failure (no retry limit)...
2018-04-03 13:36:28.036131 W [22564:48796040] TimelineMessaging::RabbitConnection -- Retrying connection on next host in line: localhost:5672
```

I would have expected Bunny to automatically recover, but it didn't and the thread remained dead and I had to kill and restart the process.

- bunny (2.9.2)
- rabbitmq-server 3.6.15-1

**Comment by michaelklishin** [comment]
This is [by design](https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/cruby/socket.rb#L65).

Last time that part of the reader loop has changed in 008afecbd8986a3caab40a018beb33fff7ed004b, and I suspect it really dates back to 2012 or so. This
decision can be revisited. Curiously Ruby's [`IO.select` docs](http://www.rubydoc.info/stdlib/core/IO.select) these days provide examples that retry regardless of what `select(2)` returns.

**Comment by michaelklishin** [comment]
@rgaufman I changed things to retry continuously in scenarios such as this one. Thank you for suggesting it. Please give master a try and let us know how it goes!

**Comment by michaelklishin** [comment]
So the change in 8572578c90d672e8fb67c127dbf4707b5fabfc08 makes user-configured read timeouts effectively useless. I'll think of a different way of improving the retry mechanism.

**Comment by michaelklishin** [comment]
An alternative that I would accept would be making `Timeout::Error` to initiate connection recovery.
That apparently is [already the case](https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/reader_loop.rb#L36) in the reader loop and [during connection recovery](https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/session.rb#L745).

According to the log provided, there are recovery attempts:

```
2018-04-03 13:35:21.183805 W [22564:48796040] TimelineMessaging::RabbitConnection -- Will recover from a network failure (no retry limit)...
2018-04-03 13:35:47.997344 W [22564:48796040] TimelineMessaging::RabbitConnection -- Retrying connection on next host in line: localhost:5672
```

so there is no evidence of a "dead thread" and my original hypothesis does not apply. Without
a way to reproduce I'm not sure what else can be done.

**Comment by rgaufman** [comment]
Thank you for looking into this. This is all the logs show. After the above, publish stops working silently and messages no longer reach RabbitMQ :( - I'll try to find a way to reproduce reliably, but this happens randomly on the very heavily loaded machines.

Any ideas where to add extra logging to help collect more information next time this happens?

**Comment by michaelklishin** [comment]
Bunny has debug logging that can be enabled using an environment variable: `BUNNY_LOG_LEVEL=debug`. Server logs is another important source of information.

"Publishes stopped coming through" can mean a channel-level exception and not an unsuccessful recovery. Those are visible in server logs and quickly result in thrown exceptions on the client end.

**Comment by rgaufman** [comment]
I had this happen again today, this time I was adding some new vhosts and RabbitMQ temporarily hung, I started seeing all of my Bunny processes die, my sidekiq tasks die, Rails errors, etc:

Rails Log:
```
E, [2018-04-23T12:56:46.879065 #22868] ERROR -- : Could not execute command from ({"command"=>"message", "identifier"=>"{\"channel\":\"AgentsChannel\"}", "data"=>"{\"ids\":[\"572b40e23d1f9239a23ad681\"],\"action\":\"refresh\"}"}) [Timeout::Error - IO timeout when reading 7 bytes]: /var/lib/gems/2.5.0/gems/bunny-2.9.2/lib/bunny/cruby/socket.rb:65:in `rescue in read_fully' | /var/lib/gems/2.5.0/gems/bunny-2.9.2/lib/bunny/cruby/socket.rb:53:in `read_fully' | /var/lib/gems/2.5.0/gems/bunny-2.9.2/lib/bunny/transport.rb:214:in `read_fully' | /var/lib/gems/2.5.0/gems/bunny-2.9.2/lib/bunny/transport.rb:236:in `read_next_frame' | /var/lib/gems/2.5.0/gems/bunny-2.9.2/lib/bunny/session.rb:1127:in `init_connection'
```

Bunny Message Consumer Process:
```
2018-04-23 12:58:05.540760 E [13707:12682680 transport.rb:216] TimelineMessaging::RabbitConnection -- Got an exception when receiving data: IO timeout when reading 7 bytes (Timeout::Error)
```

journalctl logs:
```
Apr 23 13:02:16 Timeline systemd[1]: timeline-messaging.service: Main process exited, code=exited, status=1/FAILURE
Apr 23 13:02:16 Timeline systemd[1]: timeline-messaging.service: Unit entered failed state.
Apr 23 13:02:16 Timeline systemd[1]: timeline-messaging.service: Failed with result 'exit-code'.
Apr 23 13:02:31 Timeline systemd[1]: timeline-messaging.service: Service hold-off time over, scheduling restart.
Apr 23 13:02:31 Timeline systemd[1]: Stopped Timeline Message Consumer.
Apr 23 13:02:31 Timeline systemd[1]: Started Timeline Message Consumer.
Apr 23 13:02:34 Timeline sudo[28413]: deployer : TTY=unknown ; PWD=/data/deployer/timeline/current ; USER=root ; COMMAND=/usr/sbin/rabbitmqctl -q status
Apr 23 13:02:34 Timeline runuser[28417]: pam_unix(runuser:session): session opened for user rabbitmq by (uid=0)
Apr 23 13:02:59 Timeline runuser[28417]: pam_unix(runuser:session): session closed for user rabbitmq
Apr 23 13:03:45 Timeline systemd[1]: timeline-messaging.service: Main process exited, code=exited, status=1/FAILURE
Apr 23 13:03:45 Timeline systemd[1]: timeline-messaging.service: Unit entered failed state.
Apr 23 13:03:45 Timeline systemd[1]: timeline-messaging.service: Failed with result 'exit-code'.
Apr 23 13:04:00 Timeline systemd[1]: timeline-messaging.service: Service hold-off time over, scheduling restart.
```

sidekiq logs:
```
2018-04-23T12:10:07.529Z 12246 TID-i27ey WARN: {"context":"Job raised exception","job":{"class":"UserNotifyAgentsWorker","args":[{"$oid":"55c25d6873657239f2000001"},"sign_out","delete"],"retry":3,"queue":"low","backtrace":true,"jid":"e59bc33275828f257e99310d","created_at":1524483930.806818,"enqueued_at":1524484644.014886,"error_message":"IO timeout when reading 7 bytes","error_class":"Timeout::Error","failed_at":1524484607.2263095,"retry_count":0,"error_backtrace":["/var/lib/gems/2.5.0/gems/bunny-2.9.2/lib/bunny/cruby/socket.rb:65:in `rescue in read_fully'","/var/lib/gems/2.5.0/gems/bunny-2.9.2/lib/bunny/cruby/socket.rb:53:in `read_fully'","/var/lib/gems/2.5.0/gems/bunny-2.9.2/lib/bunny/transport.rb:214:in `read_fully'","/var/lib/gems/2.5.0/gems/bunny-2.9.2/lib/bunny/transport.rb:236:in `read_next_frame'","/var/lib/gems/2.5.0/gems/bunny-2.9.2/lib/bunny/session.rb:1127:in `init_connection'","/var/lib/gems/2.5.0/gems/bunny-2.9.2/lib/bunny/session.rb:310:in `start'","/data/deployer/.bundle/ruby/2.5.0/timeline_messaging-591d2353d8a6/lib/timeline_messaging/rabbit_connection.rb:36:in `connect'","/data/deployer/.bundle/ruby/2.5.0/timeline_messaging-591d2353d8a6/lib/timeline_messaging/rabbit_connection.rb:22:in `initialize'","/data/deployer/.bundle/ruby/2.5.0/timeline_messaging-591d2353d8a6/lib/timeline_messaging.rb:151:in `new'","/data/deployer/.bundle/ruby/2.5.0/timeline_messaging-591d2353d8a6/lib/timeline_messaging.rb:151:in `exchange'","/data/deployer/.bundle/ruby/2.5.0/timeline_messaging-591d2353d8a6/lib/timeline_messaging.rb:200:in `send'","/data/deployer/timeline/current/app/models/user/user.rb:185:in `block (2 levels) in notify_agents'","/var/lib/gems/2.5.0/gems/mongoid-6.4.0/lib/mongoid/contextual/mongo.rb:705:in `yield_document'","/var/lib/gems/2.5.0/gems/mongoid-6.4.0/lib/mongoid/contextual/mongo.rb:134:in `block in each'","/var/lib/gems/2.5.0/gems/mongoid-6.4.0/lib/mongoid/contextual/mongo.rb:133:in `each'","/var/lib/gems/2.5.0/gems/mongoid-6.4.0/lib/mongoid/contextual/mongo.rb:133:in `each'","/var/lib/gems/2.5.0/gems/mongoid-6.4.0/lib/mongoid/contextual.rb:20:in `each'","/data/deployer/timeline/current/app/models/user/user.rb:172:in `block in notify_agents'","/var/lib/gems/2.5.0/gems/mongoid-6.4.0/lib/mongoid/contextual/mongo.rb:705:in `yield_document'","/var/lib/gems/2.5.0/gems/mongoid-6.4.0/lib/mongoid/contextual/mongo.rb:134:in `block in each'","/var/lib/gems/2.5.0/gems/mongo-2.5.1/lib/mongo/collection/view/iterable.rb:46:in `block in each'","/var/lib/gems/2.5.0/gems/mongo-2.5.1/lib/mongo/cursor.rb:121:in `block in each'","/var/lib/gems/2.5.0/gems/mongo-2.5.1/lib/mongo/cursor.rb:121:in `each'","/var/lib/gems/2.5.0/gems/mongo-2.5.1/lib/mongo/cursor.rb:121:in `each'","/var/lib/gems/2.5.0/gems/mongo-2.5.1/lib/mongo/collection/view/iterable.rb:45:in `each'","/var/lib/gems/2.5.0/gems/mongoid-6.4.0/lib/mongoid/query_cache.rb:222:in `each'","/var/lib/gems/2.5.0/gems/mongoid-6.4.0/lib/mongoid/contextual/mongo.rb:133:in `each'","/var/lib/gems/2.5.0/gems/mongoid-6.4.0/lib/mongoid/contextual.rb:20:in `each'","/data/deployer/timeline/current/app/models/user/user.rb:170:in `notify_agents'","/data/deployer/timeline/current/app/workers/user_notify_agents_worker.rb:9:in `perform'","/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:187:in `execute_job'","/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:169:in `block (2 levels) in process'","/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'","/var/lib/gems/2.5.0/gems/newrelic_rpm-5.0.0.342/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'","/var/lib/gems/2.5.0/gems/newrelic_rpm-5.0.0.342/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:369:in `perform_action_with_newrelic_trace'","/var/lib/gems/2.5.0/gems/newrelic_rpm-5.0.0.342/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'","/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'","/var/lib/gems/2.5.0/gems/sidekiq-middleware-0.3.0/lib/sidekiq-middleware/server/unique_jobs.rb:18:in `call'","/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'","/var/lib/gems/2.5.0/gems/bugsnag-6.7.1/lib/bugsnag/integrations/sidekiq.rb:23:in `call'","/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'","/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:133:in `invoke'","/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:168:in `block in process'","/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:139:in `block (6 levels) in dispatch'","/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:98:in `local'","/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:138:in `block (5 levels) in dispatch'","/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:42:in `block in call'","/var/lib/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:87:in `wrap'","/var/lib/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/reloader.rb:73:in `block in wrap'","/var/lib/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:87:in `wrap'","/var/lib/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/reloader.rb:72:in `wrap'","/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:41:in `call'","/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:134:in `block (4 levels) in dispatch'","/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:199:in `stats'","/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:129:in `block (3 levels) in dispatch'","/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/job_logger.rb:8:in `call'","/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:128:in `block (2 levels) in dispatch'","/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:73:in `global'","/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:127:in `block in dispatch'","/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:48:in `with_context'","/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:42:in `with_job_hash_context'","/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:126:in `dispatch'","/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:167:in `process'","/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:85:in `process_one'","/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:73:in `run'","/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:16:in `watchdog'","/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:25:in `block in safe_thread'"]},"jobstr":"{\"class\":\"UserNotifyAgentsWorker\",\"args\":[{\"$oid\":\"55c25d6873657239f2000001\"},\"sign_out\",\"delete\"],\"retry\":3,\"queue\":\"low\",\"backtrace\":true,\"jid\":\"e59bc33275828f257e99310d\",\"created_at\":1524483930.806818,\"enqueued_at\":1524484644.014886,\"error_message\":\"IO timeout when reading 7 bytes\",\"error_class\":\"Timeout::Error\",\"failed_at\":1524484607.2263095,\"retry_count\":0,\"error_backtrace\":[\"/var/lib/gems/2.5.0/gems/bunny-2.9.2/lib/bunny/cruby/socket.rb:65:in `rescue in read_fully'\",\"/var/lib/gems/2.5.0/gems/bunny-2.9.2/lib/bunny/cruby/socket.rb:53:in `read_fully'\",\"/var/lib/gems/2.5.0/gems/bunny-2.9.2/lib/bunny/transport.rb:214:in `read_fully'\",\"/var/lib/gems/2.5.0/gems/bunny-2.9.2/lib/bunny/transport.rb:236:in `read_next_frame'\",\"/var/lib/gems/2.5.0/gems/bunny-2.9.2/lib/bunny/session.rb:1127:in `init_connection'\",\"/var/lib/gems/2.5.0/gems/bunny-2.9.2/lib/bunny/session.rb:310:in `start'\",\"/data/deployer/.bundle/ruby/2.5.0/timeline_messaging-591d2353d8a6/lib/timeline_messaging/rabbit_connection.rb:36:in `connect'\",\"/data/deployer/.bundle/ruby/2.5.0/timeline_messaging-591d2353d8a6/lib/timeline_messaging/rabbit_connection.rb:22:in `initialize'\",\"/data/deployer/.bundle/ruby/2.5.0/timeline_messaging-591d2353d8a6/lib/timeline_messaging.rb:151:in `new'\",\"/data/deployer/.bundle/ruby/2.5.0/timeline_messaging-591d2353d8a6/lib/timeline_messaging.rb:151:in `exchange'\",\"/data/deployer/.bundle/ruby/2.5.0/timeline_messaging-591d2353d8a6/lib/timeline_messaging.rb:200:in `send'\",\"/data/deployer/timeline/current/app/models/user/user.rb:185:in `block (2 levels) in notify_agents'\",\"/var/lib/gems/2.5.0/gems/mongoid-6.4.0/lib/mongoid/contextual/mongo.rb:705:in `yield_document'\",\"/var/lib/gems/2.5.0/gems/mongoid-6.4.0/lib/mongoid/contextual/mongo.rb:134:in `block in each'\",\"/var/lib/gems/2.5.0/gems/mongoid-6.4.0/lib/mongoid/contextual/mongo.rb:133:in `each'\",\"/var/lib/gems/2.5.0/gems/mongoid-6.4.0/lib/mongoid/contextual/mongo.rb:133:in `each'\",\"/var/lib/gems/2.5.0/gems/mongoid-6.4.0/lib/mongoid/contextual.rb:20:in `each'\",\"/data/deployer/timeline/current/app/models/user/user.rb:172:in `block in notify_agents'\",\"/var/lib/gems/2.5.0/gems/mongoid-6.4.0/lib/mongoid/contextual/mongo.rb:705:in `yield_document'\",\"/var/lib/gems/2.5.0/gems/mongoid-6.4.0/lib/mongoid/contextual/mongo.rb:134:in `block in each'\",\"/var/lib/gems/2.5.0/gems/mongo-2.5.1/lib/mongo/collection/view/iterable.rb:46:in `block in each'\",\"/var/lib/gems/2.5.0/gems/mongo-2.5.1/lib/mongo/cursor.rb:121:in `block in each'\",\"/var/lib/gems/2.5.0/gems/mongo-2.5.1/lib/mongo/cursor.rb:121:in `each'\",\"/var/lib/gems/2.5.0/gems/mongo-2.5.1/lib/mongo/cursor.rb:121:in `each'\",\"/var/lib/gems/2.5.0/gems/mongo-2.5.1/lib/mongo/collection/view/iterable.rb:45:in `each'\",\"/var/lib/gems/2.5.0/gems/mongoid-6.4.0/lib/mongoid/query_cache.rb:222:in `each'\",\"/var/lib/gems/2.5.0/gems/mongoid-6.4.0/lib/mongoid/contextual/mongo.rb:133:in `each'\",\"/var/lib/gems/2.5.0/gems/mongoid-6.4.0/lib/mongoid/contextual.rb:20:in `each'\",\"/data/deployer/timeline/current/app/models/user/user.rb:170:in `notify_agents'\",\"/data/deployer/timeline/current/app/workers/user_notify_agents_worker.rb:9:in `perform'\",\"/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:187:in `execute_job'\",\"/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:169:in `block (2 levels) in process'\",\"/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'\",\"/var/lib/gems/2.5.0/gems/newrelic_rpm-5.0.0.342/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'\",\"/var/lib/gems/2.5.0/gems/newrelic_rpm-5.0.0.342/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:369:in `perform_action_with_newrelic_trace'\",\"/var/lib/gems/2.5.0/gems/newrelic_rpm-5.0.0.342/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'\",\"/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\",\"/var/lib/gems/2.5.0/gems/sidekiq-middleware-0.3.0/lib/sidekiq-middleware/server/unique_jobs.rb:18:in `call'\",\"/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\",\"/var/lib/gems/2.5.0/gems/bugsnag-6.7.1/lib/bugsnag/integrations/sidekiq.rb:23:in `call'\",\"/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\",\"/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:133:in `invoke'\",\"/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:168:in `block in process'\",\"/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:139:in `block (6 levels) in dispatch'\",\"/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:98:in `local'\",\"/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:138:in `block (5 levels) in dispatch'\",\"/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:42:in `block in call'\",\"/var/lib/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:87:in `wrap'\",\"/var/lib/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/reloader.rb:73:in `block in wrap'\",\"/var/lib/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:87:in `wrap'\",\"/var/lib/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/reloader.rb:72:in `wrap'\",\"/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:41:in `call'\",\"/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:134:in `block (4 levels) in dispatch'\",\"/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:199:in `stats'\",\"/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:129:in `block (3 levels) in dispatch'\",\"/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/job_logger.rb:8:in `call'\",\"/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:128:in `block (2 levels) in dispatch'\",\"/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:73:in `global'\",\"/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:127:in `block in dispatch'\",\"/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:48:in `with_context'\",\"/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:42:in `with_job_hash_context'\",\"/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:126:in `dispatch'\",\"/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:167:in `process'\",\"/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:85:in `process_one'\",\"/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:73:in `run'\",\"/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:16:in `watchdog'\",\"/var/lib/gems/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:25:in `block in safe_thread'\"]}"}
2018-04-23T12:10:07.529Z 12246 TID-i27ey WARN: RuntimeError: this connection is not open. Was Bunny::Session#start invoked? Is automatic recovery enabled?
2018-04-23T12:10:07.529Z 12246 TID-i27ey WARN: /var/lib/gems/2.5.0/gems/bunny-2.9.2/lib/bunny/session.rb:351:in `create_channel'
/data/deployer/.bundle/ruby/2.5.0/timeline_messaging-591d2353d8a6/lib/timeline_messaging/rabbit_channel.rb:11:in `initialize'
/data/deployer/.bundle/ruby/2.5.0/timeline_messaging-591d2353d8a6/lib/timeline_messaging.rb:153:in `new'
/data/deployer/.bundle/ruby/2.5.0/timeline_messaging-591d2353d8a6/lib/timeline_messaging.rb:153:in `exchange'
/data/deployer/.bundle/ruby/2.5.0/timeline_messaging-591d2353d8a6/lib/timeline_messaging.rb:200:in `send'
/data/deployer/timeline/current/app/models/user/user.rb:185:in `block (2 levels) in notify_agents'
```

So it does seeem like Bunny doesn't seem to be able to gracefully recover from a Timeout exception. Any ideas?
