### ISSUE TITLE
Exception raised when creating channel

### ISSUE THREAD

**Issue by tomtaylor** [ruby-amqp/bunny#92]
With Bunny on latest master (#7e6b8a), when I run `Bunny.new.create_channel` the following exception is raised:

```
/usr/local/opt/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/bundler/gems/bunny-7e6b8ab9e118/lib/bunny/session.rb:480:in `next_channel_id': undefined method `next_channel_id' for nil:NilClass (NoMethodError)
  from /usr/local/opt/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/bundler/gems/bunny-7e6b8ab9e118/lib/bunny/channel.rb:156:in `initialize'
  from /usr/local/opt/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/bundler/gems/bunny-7e6b8ab9e118/lib/bunny/session.rb:168:in `new'
  from /usr/local/opt/rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/bundler/gems/bunny-7e6b8ab9e118/lib/bunny/session.rb:168:in `create_channel'
  from run.rb:4:in `<main>'
```

**Comment by mancvso** [comment]
2015 and I was bitten bi this.

**Comment by michaelklishin** [comment]
I'm going to add a check that would throw a more useful exception, since we pretty much know the first thing people do with a connection is opening a channel.
